---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: 'https://github.com/jorisroovers/gitlint.git'
    rev: v0.11.0
    hooks:
      - id: gitlint
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: lint-dhall
        name: 'Check dhall lint'
        entry: 'make check-lint'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: make-examples
        name: 'Make examples'
        entry: 'make examples'
        language: system
        pass_filenames: false