---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: 'https://github.com/jorisroovers/gitlint.git'
    rev: v0.11.0
    hooks:
      - id: gitlint
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: format-dhall
        name: 'Run dhall formatter'
        entry: 'make fmt'
        language: system
        pass_filenames: false
        types: [file]
  - repo: local
    hooks:
      - id: lint-dhall
        name: 'Run dhall lint'
        entry: 'make lint'
        language: system
        pass_filenames: false
        types: [file]
  - repo: local
    hooks:
      - id: check-asciidoc
        name: 'Check asciidoc'
        entry: 'asciidoctor --failure-level=WARNING -o /dev/null'
        pass_filenames: true
        language: system
        files: '.*\.adoc'
