apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: basic1-srv
      namespace: basic1
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 9999
      selector:
        app: basic1
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        haproxy.router.openshift.io/timeout: "60s"
      name: basic1-route
      namespace: basic1
    spec:
      host: basic1.cirb.lan
      path: /
      to:
        kind: Service
        name: basic1-srv
        weight: 100
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: basic1
      namespace: basic1
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: basic1
      template:
        metadata:
          labels:
            app: basic1
          name: basic1
        spec:
          containers:
            - image: cicd-docker.repository.irisnet.be/basic-app:0.2
              name: basic1
              ports:
                - containerPort: 9999
kind: List
