apiVersion: v1
items:
  - apiVersion: v1
    kind: Project
    metadata:
      annotations:
        openshift.io/display-name: cicd doc for docs.cicd.cirb.lan
        openshift.io/requester: cicd
      name: cicd-doc-dev
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: cicd-doc-dev-quota
      namespace: cicd-doc-dev
    spec:
      hard:
        limits.cpu: '2'
        limits.memory: "2Gi"
        requests.cpu: '1'
        requests.memory: "1Gi"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cicd-doc-dev
      namespace: cicd-doc-dev
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: cicd-doc-dev
      template:
        metadata:
          labels:
            app: cicd-doc-dev
          name: cicd-doc-dev
        spec:
          containers:
            - env:
                - name: NIX_PATH
                  value: nixpkgs-overlays=http://stash.cirb.lan/CICD/nixpkgs-overlays/archive/master.tar.gz
              image: cicd-docker.repository.irisnet.be/cicd-docs
              name: cicd-docs
              ports:
                - containerPort: 8080
              volumeMounts:
                - mountPath: /etc/data
                  name: test-data
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: nixery-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "10Gi"
      storageClassName: slow
      volumeName: pv-nfs-sbx-vol04
  - apiVersion: v1
    data:
      test.conf: "Here is the content of the test.conf file\n\nCICD & Middleware"
    kind: ConfigMap
    metadata:
      name: test-data
  - apiVersion: v1
    data:
      test.crt: Please encrypt this file
    kind: Secret
    metadata:
      name: test.crt
    type: Opaque
  - apiVersion: v1
    kind: Service
    metadata:
      name: cicd-doc-dev-srv
      namespace: cicd-doc-dev
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        app: cicd-doc-dev
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        haproxy.router.openshift.io/timeout: "60s"
      name: cicd-doc-dev-route
      namespace: cicd-doc-dev
    spec:
      host: docs.cicd.cirb.lan
      to:
        kind: Service
        name: cicd-doc-dev-srv
        weight: 100
kind: List
