apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: argocd
spec:
  destination:
    namespace: app1-dev
    server: https://kubernetes.default.svc
  project: cicd
  source:
    path: sbx/application/app1/dev
    repoURL: http://stash.cirb.lan/scm/oc/projects.git
    targetRevision: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
